# Generated by Django 6.0.1 on 2026-02-10 15:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gear',
            options={'ordering': ['-created_at'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Список товарів'},
        ),
        migrations.AlterModelOptions(
            name='gearcategory',
            options={'verbose_name': 'Тип товару', 'verbose_name_plural': 'Gears (Типи товарів)'},
        ),
        migrations.AlterModelOptions(
            name='sport',
            options={'verbose_name': 'Напрямок', 'verbose_name_plural': 'Напрямки (Категорії)'},
        ),
        migrations.AddField(
            model_name='sport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sports/', verbose_name='Фото для картки'),
        ),
        migrations.AlterField(
            model_name='gear',
            name='brand',
            field=models.CharField(max_length=100, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='gear',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gear.gearcategory', verbose_name='Тип товару'),
        ),
        migrations.AlterField(
            model_name='gear',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='gear',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='gear',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='gear',
            name='in_stock',
            field=models.BooleanField(default=True, verbose_name='В наявності'),
        ),
        migrations.AlterField(
            model_name='gear',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='gear',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='gear',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=3, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='gearcategory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Назва категорії'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(blank=True, verbose_name='Повний текст'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='gear',
            field=models.ManyToManyField(blank=True, related_name='sports', to='gear.gear', verbose_name='Товари для цього напрямку'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='icon',
            field=models.CharField(help_text='Наприклад: fa-hiking', max_length=100, verbose_name='Іконка (клас або символ)'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва напрямку'),
        ),
    ]
