# Generated by Django 6.0.1 on 2026-02-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0002_alter_gear_options_alter_gearcategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sport',
            name='gear',
        ),
        migrations.AddField(
            model_name='gear',
            name='sports',
            field=models.ManyToManyField(blank=True, related_name='gears', to='gear.sport', verbose_name='Види спорту (Напрямки)'),
        ),
    ]
