# Generated by Django 6.0.1 on 2026-03-10 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0003_remove_sport_gear_gear_sports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gear.gearcategory', verbose_name='Тип товару (Технічна категорія)'),
        ),
        migrations.AlterField(
            model_name='gear',
            name='sports',
            field=models.ManyToManyField(help_text="Оберіть напрямок, щоб товар з'явився у відповідній картці на головній", related_name='gears', to='gear.sport', verbose_name='Популярні напрямки (Для виводу по центру)'),
        ),
    ]
