# Generated by Django 6.0.1 on 2026-03-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0004_alter_gear_category_alter_gear_sports'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Посилання на фото'),
        ),
    ]
