# Generated by Django 6.0.1 on 2026-03-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0005_gear_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_telegram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram'),
        ),
    ]
