# Generated by Django 6.0.1 on 2026-03-24 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0006_order_customer_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gear.gearcategory', verbose_name='Тип товару'),
        ),
        migrations.AlterField(
            model_name='gear',
            name='sports',
            field=models.ManyToManyField(related_name='gears', to='gear.sport', verbose_name='Популярні напрямки'),
        ),
        migrations.CreateModel(
            name='RentalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ціна за добу (грн)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='rentals/', verbose_name='Фото')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступне для оренди')),
                ('sport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gear.sport', verbose_name='Вид спорту')),
            ],
            options={
                'verbose_name': 'Позиція для оренди',
                'verbose_name_plural': 'Інвентар для оренди',
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name="Ім'я клієнта")),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('customer_telegram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram')),
                ('start_date', models.DateField(verbose_name='Дата початку')),
                ('end_date', models.DateField(verbose_name='Дата закінчення')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сума оренди')),
                ('status', models.CharField(choices=[('pending', 'Очікує підтвердження'), ('confirmed', 'Підтверджено'), ('active', 'Активна'), ('completed', 'Завершена'), ('cancelled', 'Скасована')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('stripe_session_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe Session ID')),
                ('rental_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gear.rentalitem', verbose_name='Спорядження')),
            ],
            options={
                'verbose_name': 'Оренда',
                'verbose_name_plural': 'Оренди',
                'ordering': ['-created_at'],
            },
        ),
    ]
