# Generated by Django 6.0.1 on 2026-03-24 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0007_alter_gear_category_alter_gear_sports_rentalitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='rentalitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='rentalitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='rentalitem',
            name='price_per_day',
        ),
        migrations.RemoveField(
            model_name='rentalitem',
            name='sport',
        ),
        migrations.AddField(
            model_name='gear',
            name='is_rentable',
            field=models.BooleanField(default=False, verbose_name='Доступний для оренди'),
        ),
        migrations.AddField(
            model_name='gear',
            name='price_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ціна оренди за добу (грн)'),
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='gear',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rental_item', to='gear.gear', verbose_name='Товар зі списку'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sport',
            name='icon',
            field=models.CharField(max_length=100, verbose_name='Іконка (клас або символ)'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sports/', verbose_name='Фото'),
        ),
    ]
