# Generated by Django 6.0.1 on 2026-03-24 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0008_remove_rentalitem_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='rental_item',
        ),
        migrations.AddField(
            model_name='rental',
            name='gear',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gear.gear', verbose_name='Товар'),
            preserve_default=False,
        ),
    ]
