# Generated by Django 6.0.1 on 2026-05-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0009_remove_rental_rental_item_rental_gear'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Telegram username')),
                ('chat_id', models.CharField(max_length=50, verbose_name='Chat ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Telegram користувач',
                'verbose_name_plural': 'Telegram користувачі',
            },
        ),
    ]
