from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("login/", views.user_login, name="login"),
    path("register/", views.user_register, name="register"),
    path("logout/", views.user_logout, name="logout"),
    path("gear/<int:gear_id>/", views.gear_detail, name="gear_detail"),
    path("category/<int:category_id>/", views.category_gear, name="category_gear"),
    path("sport/<int:sport_id>/", views.sport_detail, name="sport_detail"),
    path("news/", views.news_list, name="news"),
    path("news/<int:news_id>/", views.news_detail, name="news_detail"),
    path("search/", views.search_gear, name="search_gear"),
    path("gear-table/", views.gear_table, name="gear_table"),
    path("beginners-guide/", views.beginners_guide, name="beginners_guide"),
    path("cart/", views.cart_detail, name="cart_detail"),
    path("cart/add/<int:gear_id>/", views.add_to_cart, name="add_to_cart"),
    path("cart/remove/<int:gear_id>/", views.remove_from_cart, name="remove_from_cart"),
    path("cart/checkout/", views.checkout_cart, name="checkout_cart"),
    path("order-success/", views.order_success, name="order_success"),
    path("quick-order/<int:gear_id>/", views.quick_order, name="quick_order"),
    path("create-payment-intent/", views.create_payment_intent, name="create_payment_intent"),
    path("create-rental-payment-intent/", views.create_rental_payment_intent, name="create_rental_payment_intent"),
    path("rental/", views.rental_list, name="rental_list"),
    path("rental/<int:item_id>/", views.rental_checkout, name="rental_checkout"),
    path("rental/success/<int:rental_id>/", views.rental_success, name="rental_success"),
    path("api/rental-price/", views.rental_price_api, name="rental_price_api"),
    path("api/ai/", views.query_openrouter, name="query_openrouter"),
    path("api/calculate-gear/", views.calculate_gear_api, name="calculate_gear_api"),
    path("api/gear/<int:gear_id>/image/", views.get_gear_image_redirect, name="get_gear_image_redirect"),
    path("telegram-webhook/", views.telegram_webhook, name="telegram_webhook"),
]